name: hotel-app
services:
  basics:
    build: .
    ports:
      - 8081:80
    develop:
      watch:
        - action: sync
          path: ./dist/hotel-app/browser
          target: /usr/local/apache2/htdocs/
    networks:
      proxy:
        external: true
          - PRxy01
networks:
  nginxproxymanager:
    name: PRxy01